# Generated by Django 5.2.5 on 2025-09-03 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='title')),
                ('summary', models.CharField(blank=True, max_length=255, verbose_name='abstract')),
                ('content_md', models.TextField(verbose_name='content')),
                ('cover', models.ImageField(blank=True, upload_to='covers/', verbose_name='img')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='create_time')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='update')),
                ('views', models.PositiveIntegerField(default=0, verbose_name='num_views')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
