# Generated by Django 5.2.5 on 2025-09-04 15:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_resume', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True, verbose_name='category_name')),
                ('slug', models.SlugField(unique=True, verbose_name='url_click')),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='content_html',
            field=models.TextField(blank=True, editable=False, verbose_name='con_HTML'),
        ),
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='web_resume.category'),
        ),
    ]
