# Generated by Django 5.2.5 on 2025-09-06 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_resume', '0002_category_article_content_html_article_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='create_time'),
        ),
    ]
