# Generated by Django 5.2.5 on 2025-09-20 14:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_resume', '0004_articleimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='series_name')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='URL_name')),
                ('desc', models.TextField(blank=True, verbose_name='series_info')),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='series_order',
            field=models.PositiveSmallIntegerField(default=0, help_text='0=首位', verbose_name='系列内顺序'),
        ),
        migrations.AddField(
            model_name='article',
            name='series',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='web_resume.series'),
        ),
    ]
