# Generated by Django 5.2.5 on 2025-09-20 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_resume', '0005_series_article_series_order_article_series'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='series_order',
            field=models.PositiveSmallIntegerField(default=0, help_text='0=首位', verbose_name='series_order'),
        ),
    ]
