# Generated by Django 5.2.5 on 2025-09-20 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_resume', '0006_alter_article_series_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['is_pinned', '-created_at']},
        ),
        migrations.AddField(
            model_name='article',
            name='is_pinned',
            field=models.BooleanField(default=False, verbose_name='置顶'),
        ),
    ]
