name: Auto Deploy to Ubuntu

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Execute remote deployment script
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.DEPLOY_KEY }}
          script: |
            set -e                 # 任何一步失败就退出
            export DJANGO_SECRET_KEY="${{ secrets.DJANGO_SECRET_KEY }}"
            cd /home/django_web/web_blog/web_blog
            git pull origin main
            source /home/django_web/venvs/blog/bin/activate
            pip install -r requirements.txt
            python manage.py migrate --noinput
            python manage.py collectstatic --noinput
            sudo /usr/bin/supervisorctl restart web_blog
